### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by pungggi** [prisma/graphcool-framework#552]
I am wondering if plan to stop supporting graphcool in favour of prisma.

The last relase is from last december..

**Comment by mpbalmeida** [comment]
I have the same feeling. Graphcool is a killer for simple and internal projects.

Using Prisma I will need another server.

**Comment by b33son** [comment]
I feel like most of their team is focusing on Prisma... Prisma is okay, but its web admin interface is limited. Plus the whole needing a server. Docker makes that a little easier though.
