### ISSUE TITLE
Deploy functions needs update to aws lambda runtime nodejs 6.10 > nodejs8.10

### ISSUE THREAD

**Issue by b3nab** [prisma/graphcool-framework#577]
For **bug reports**, please fill in the next sections:

**Current behavior**

```sh
Creating service service in cluster shared-eu-west-1... ✔
Bundling functions... ⣟
Bundling functions... 13.1s
Deploying... 776ms
There are issues with the new service definition:

  Global
    ✖ software.amazon.awssdk.services.lambda.model.InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: null; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ee0cd923-76b8-11e9-a12b-2349b42e70b4)
```

**Reproduction**

I don't know how to reproduce or fix  this bug, because in the graphcool.yml there isn't a `runtime` variable to just set to nodejs8.10.

**Expected behavior?**

It should just deploy as I do before in the pasts months without problems.
What can I do to solve this bug during the deploy of a graphcool service?

**Comment by pantharshit00** [comment]
It is fixed now

**Comment by MingFaiYau** [comment]
I also get this problem..
![image](https://user-images.githubusercontent.com/28052105/60568093-6831d280-9d9e-11e9-9b4d-bf2298ef941e.png)
How to solve it...

**Comment by Ahrengot** [comment]
Yep, same error here. Just appeared out of the blue today.

**Comment by scgrossman** [comment]
I'm also getting the same issue.

**Comment by shokimble** [comment]
So what is the fix?

**Comment by froliveira94** [comment]
So what is the fix?

**Comment by shokimble** [comment]
I've found "the fix" unfortunately it only applies to new deployments not updating existing lambda functions. If you are trying to update production code like me I think you're out of luck.

It's from @dpetrick 

https://github.com/prisma/graphcool-framework/commit/617ce95e2a4b68bc025e0d9206b5abdaf201df22#diff-0df7b5f86ea502ce516847555a3a9bed

Clearly I'm no expert on the internals but if you look at the rest of the code update seems to ignore the node runtime which would explain what's happening. Line 113 and beyond.

https://github.com/prisma/graphcool-framework/blob/master/server/backend-shared/src/main/scala/cool/graph/shared/functions/lambda/LambdaFunctionEnvironment.scala

It seems like this could be inserted between lines 128 and 129 to fix the issue

`.runtime(runtime)`


@dpetrick Are you able to help?

**Comment by romanmandryk** [comment]
This started to happen again today out of the blue.
 software.amazon.awssdk.services.lambda.model.InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions.

**Comment by romanmandryk** [comment]
Received and advice from graphcool support and it solved the issue:

"You will need to redeploy the function in a new name so that it can reset the runtime."

**Comment by shokimble** [comment]
> "You will need to redeploy the function in a new name so that it can reset the runtime."

Thanks for relaying that here @romanmandryk ... and it makes complete sense as the runtime is included in the create code but not the update code but that doesn't help when someone can't redeploy code as quickly that is calling the named functions such as in a mobile phone app.

Didn't get an ETA on it being resolved?

**Comment by josephmagara** [comment]
Can any

> Received and advice from graphcool support and it solved the issue:
> 
> "You will need to redeploy the function in a new name so that it can reset the runtime."

Please could you mind giving a bit more detail on how to do this? I'm stuck and cant figure out what needs to be done. I've renamed the function but the issue still occurs.

**Comment by shokimble** [comment]
You need to rename all your functions. Not just one. The deployment fails if even one fails.

Unfortunately for me and I'm sure many others I cant update the place the functions are called from all at once so it is not a good enough solution.

**Comment by josephmagara** [comment]
@shokimble Oh wow! That's hectic! At the very least is it a one time thing or would you need to rename your functions every time you need to deploy?

**Comment by josephmagara** [comment]
@shokimble Thank you for your help with this 😄

**Comment by josephmagara** [comment]
@shokimble @romanmandryk 
I've gone through and tried to rename all my functions but unfortunately, it's not worked. I'm guessing we're going to have to wait till this is rectified in a new graphcool-framework cli release

**Comment by benseitz** [comment]
Any news on this?

**Comment by pantharshit00** [comment]
We have deployed a fix for this: https://github.com/prisma/graphcool-framework/commit/dc274418ba663caad8c157a8d8690127e64e6541

Please test this out now 🙏

**Comment by shokimble** [comment]
Phew! Finally, thanks. 

I can confirm the deploy worked without errors. I haven't checked it actually updates your function but let's assume it does. If not I'll report back.

**Comment by Nico-L** [comment]
Hello,

I have the same issue from node6 to node 12 with a fresh install of graphcool. How do I install the fix?

Thanks

**Comment by rCollet** [comment]
Same issue here with v8.10 and renaming functions does not work for me.
